### ISSUE TITLE
Handling browser replies

### ISSUE THREAD

**Issue by dgkf** [dgkf/debugadapter#10]
Most of the architecture is in place and I'm feeling rather confident with most parts of the design. There's one last part that I'm still debating - how messages should be passed between the background (_shadow_) debug browser and the client. 

These messages could either flow

1. **background browser** -> **client** 
   although I think this would be difficult from a design perspective because the connection to the client would need to be juggled between the debug server and the browser session.
2. **background browser** -> **server** -> **client**
3. **background browser** -> **REPL** -> **server** -> **client**

I'll have to carve out some time to really sit down and draft the exact architectures and some of the pros/cons of each.

**Comment by dgkf** [comment]
I pushed up my work-in-progress code to [`dev/browser-relay`](https://github.com/dgkf/debugadapter/tree/dev/browser-relay), where there's a current attempt at an architecture that looks like this (below). For the sake of example, I'll just map out what it looks like to set a breakpoint and hit a `stopped` event looks like to illustrate the information flow:

```mermaid
sequenceDiagram
    participant Client
    participant Server
    participant REPL
    participant Browser

    Note left of REPL: debugadapter::run()
    Note left of Client: :DapContinue <br> (Client connects to adapter)
    Note left of Client: :DapToggleBreakpoint <br> (Client sets breakpoint) <br> eg on hello()
    Client ->> Server: setBreakpoint
    Note left of REPL: Enter command <br> (receive breakpoints on<br>next task callback)
    Server ->> REPL: setBreakpoint
    Note left of REPL: hello()
    REPL ->> Browser: Shadow Browser<br>launched
    Browser ->> Server: Stopped Event
    opt unimplemented
      Server ->> Client: Stopped Event
    end
```

There are a few things that feel clunky about this approach so far.

1. The Server connection needs to be passed to the Browser in a background process. Currently this works by setting a global option that is picked up by default by the forked background process. I'd prefer if this was passed directly.
2. The Server also needs to listen on the Browser port and relay messages to the Server. This means that we need to listen on two ports (from the Client on `:18721` by default and the Browser on `:18722` by default). Juggling messages on these two connections is a bit painful, so I was wondering if it's easier to communicate through the REPL session to keep all the communication through one series of communication channels. 

I think it would be best to see this implementation through to completion, but I'm not sure if I'll commit to this approach yet.

**Comment by dgkf** [comment]
Just documenting other findings while I get caught back up with where I was. I found two pain points so far, and I'm not sure what what the root cause is.

1. ~~Toggling breakpoints in my IDE doesn't seem to immediately get picked up by the adapter. There's a lag that is quite annoying before the request to set the breakpoint is emitted.
    **update:** the delay is related to 2. below, as the breakpoints are first processed in the background process before being handed off to the debugger in the foreground to be added there. They don't need to be added in the background process, so that can be disabled.~~
2. ~~[This bit of code](https://github.com/dgkf/debugadapter/blob/ce503e0476b7e2b9a970f1471129ec17682889d4/R/breakpoints.R#L29-L33) runs alarmingly slow. Setting a breakpoint takes 30s~~
    Was able to resolve this and 1. by limiting scope of `utils::findLineNum` 
3. And more a nuisance than anything, but setting a breakpoint also raises warnings when `options(warnPartialMatchArgs = TRUE)`. I think this are [raised from this call](https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/library/utils/R/findLineNum.R#L116).
   ```
   # partial argument match of 'all' to 'all.names'
   ```
   
Made some progress today to clean up some of these initial concerns. Will have to explore further on whether relaying directly from browser to adapter server is going to be a comfortable dataflow.

**Comment by sebffischer** [comment]
I have a question. From my understanding of the diagrams, the `browser()` call should be launched in the forked R process. 
However, the forked R process, that is defined here: https://github.com/dgkf/debugadapter/blob/76c0c103b5e708b01c2dcfe41bf3c6fde31a6bb0/R/browser.R#L61-L87 does not call `browser()`, but is instead called in the child process: https://github.com/dgkf/debugadapter/blob/76c0c103b5e708b01c2dcfe41bf3c6fde31a6bb0/R/browser.R#L100

(Because `parallel:::mcfork()` returns the child process in the master process and vice versa)

**Comment by sebffischer** [comment]
Also, shouldn't this callback https://github.com/dgkf/debugadapter/blob/76c0c103b5e708b01c2dcfe41bf3c6fde31a6bb0/R/browser.R#L43-L58 then only be launched in one of the processes?

**Comment by dgkf** [comment]
> I have a question. From my understanding of the diagrams, the browser() call should be launched in the forked R process.

Good spotting!

At one point I swapped out how this was working, so my guess is it just got out-of-sync with the initial architecture diagrams. Based on how messages need to be passed, it ended up being easier to run the browser in the current process and use the background process for handling all the things that need to happen outside of the user's view. 

I'm feeling better about this architecture, but it's still in flux. 

> Also, shouldn't this callback [...] then only be launched in one of the processes?

Yep, you're right. This really only needs to run in the parent process. The callback could be called after the processes split.

**Comment by dgkf** [comment]
Going to close as this discussion is mostly irrelevant now that we can transition to using the browser hook.
