### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by sebffischer** [dgkf/debugadapter#6]
As per your profile, I wanted to let you know that I think it is great that you are working on that. 
I would really love to be able to have a better R debugger in neovim! :)

**Comment by dgkf** [comment]
Thank you for the kind words - always appreciated! Working toward debugging in neovim is my selfish goal here too, so hopefully we end up with something serviceable.

Right now the project is still in its infancy with just a few of the requests being handled for the protocol. Once it's more mature I'll definitely be leaning on feedback to steer improvements regarding use cases that I might not be aware of.

Closing the issue, but thanks again. Please continue to revisit the project and monitor progress. Contributions are always welcome if this straddles technologies that you're familiar with and want to see things move faster.

**Comment by ltuijnder** [comment]
Hi also wanted to let you know that I have interest in this project. I am also looking into improving my R experience inside nvim. Though of course, this project could be of service to any DAP client :). 

I do not have that much experience (or any 😅) in the lsp/dap world so I do not think I will be able to contribute immediately but I looking forward to where this project will go.

**Comment by dgkf** [comment]
Thanks for saying this @ltuijnder. Even if not through code contributions, I'm sure the project would benefit from help reviewing documentation, usage instructions and providing bug reports.
